version: 0.0
os: linux
files:
 - source: /
   destination: /home/ubuntu/portfolio-frontend
permissions:
 - object: /home/ubuntu/portfolio-frontend
   pattern: '**'
   mode: '0755'
   owner: ubuntu
   group: ubuntu
   type:
     - file
     - directory
hooks:
  
  ApplicationStart:
    - location: deploy.sh
      timeout: 300
      runas: ubuntu