version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo Installing dependencies...

  build:
    commands:
      - echo Build started on `date`
      - npm install
      - npm run build || echo "No build step"

  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - '**/*'
    - appspec.yml
    - scripts/deploy.sh
